name: tarik_workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      NAME: "tarik"
      EMAIL: "tarik.elhaiti@gmail.com"
      

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: lidt repository file
        run: ls -al
      

      - name: Saluer l'utilisateur ${{ env.NAME }}
        run: |
          echo " Hello $NAME "
          echo " Is this your email: $EMAIL ? "
