on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: mention job 1
        run : echo " My name is ${{ github.job }} "
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: mention job 2
        run : echo " my name is  ${{ github.job }} "
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: mention job 3
        run : echo " my name is  ${{ github.job }} "
  job_4:
    runs-on: ubuntu-latest
    needs:
      - job_2
      - job_3
    steps:
      - name: mention job 4
        run : echo " my name is  ${{ github.job }} "
      
        
