name: use-matrix-in-nodejs

on:
  workflow_dispatch:

jobs:
  job_1: 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [14.x, 15.x, 16.x]

        exclude:
          # On enlève les combinaisons qui cassent
          - os: macos-latest
            node_version: 14.x
          - os: macos-latest
            node_version: 15.x

        include:
          # On ajoute un cas spécial (bonus)
          - os: ubuntu-latest
            node_version: 18.x
            extra: "special test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Check Node.js version
        run: node -v

      - name: Show extra if defined
        run: echo "Extra: ${{ matrix.extra || 'none' }}"
