on:
  push: &map
    branches:
      - main
      - release/*
    paths:
      - src/**
  pull_request:
    <<: *map
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4
     - name: run test
       run: npm test
